field.storage.*.*.third_party.field_encrypt:
  type: mapping
  label: 'Field encrypt setting'
  mapping:
    encrypt:
      type: boolean
      label: 'Encrypt'

field_encrypt.settings:
  type: config_object
  label: 'Field Encrypt Settings'
  mapping:
    default_properties:
      type: sequence
      label: 'Field types'
      sequence:
        type: sequence
        label: 'Properties to encrypt'
        sequence:
          type: string
          label: 'Property name'

